version: "3.7"
services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    environment:
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - "80:5000"
